---
- name: Copy the Junos Exporter systemd service file
  template:
    src: junos_exporter.service.j2
    dest: /etc/systemd/system/junos_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart junos exporter

- name: Copy configuration file
  template:
    src: config.yml.j2
    dest: /etc/junos_exporter/config.yml
    owner: root
    group: root
    mode: 0644
  notify:
    - reload junos exporter
