---
# tasks file for ansible-role-junos-exporter
- include: preflight.yml
  tags:
    - junos_exporter_install
    - junos_exporter_configure
    - junos_exporter_run

- include: install.yml
  tags:
    - junos_exporter_install

- include: configure.yml
  tags:
    - junos_exporter_configure

- name: Make sure junos_exporter service is started and enabled
  systemd:
    daemon_reload: true
    name: junos_exporter
    state: started
    enabled: true
  tags:
    - junos_exporter_run
